#!/usr/bin/python
# -*- coding: utf-8 -*-
# 该脚本主要用于自动生成中断处理程序

# trap which has error number
trap_with_errno = [8, 10, 11, 12, 13, 14, 17]

print("# generated by vectors.py, please do not edit!")
print("# trap handler vectors!\n")

print(".code32")
print(".section .text")
print(".global trap_handlers")
for i in range(256):
    print(".global trap_handler{0}".format(i))
    print("trap_handler{0}:".format(i))
    if i not in trap_with_errno:
        print("    pushl $0")
    print("    pushl ${0}".format(i))
    print("    jmp trap_handlers\n")

print("# trap handler vectors table")
print(".section .data")
print(".global trap_handlers_table")
print("trap_handlers_table:")
for i in range(256):
    print("    .long trap_handler{0}".format(i))

# 输出格式
# .code32
# .section .text
# .global trap_handlers
# .global trap_handler0
# trap_handler0
#     pushl 0
#     pushl $0
#     pushl $0
#     jmp trap_handlers
#
#   ..........
#
# .section .data
# .global trap_handlers_table
# trap_handlers_table:
#     .long trap_handler0
#     .long trap_handler1
#     .long trap_handler2
#     .long trap_handler3
#   ..........
# 输出格式
